language: ruby
cache: bundler

rvm:
  - 2.0.0

script:
  - xvfb-run --server-args="-screen 0 1024x768x24" bundle exec rake

notifications:
  email:
    recipients:
      - slabounty@gmail.com
    on_failure: change
    on_success: never
